## 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and convenient for the programmer. As we don’t need to write the same code again and again for different programs.

There are several use of python library.

1.Code Reusability: Libraries provide a set of functions and modules that can be reused across different projects. This helps save time and effort by leveraging existing solutions instead of reinventing the wheel.

2.Efficiency: Libraries are often developed and optimized by experts, which can lead to more efficient and performant code. Developers can benefit from well-tested and optimized implementations of common algorithms and functionalities.

## 2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store and manipulate collections of elements, but there are several key differences between them. Here are some of the main distinctions:

1.Homogeneity:

List: Python lists can contain elements of different data types. You can have a mix of integers, floats, strings, or other objects in a single list.
NumPy Array: NumPy arrays are homogeneous, meaning all elements must be of the same data type. This homogeneity allows for more efficient storage and operations.

2.Memory Efficiency:

List: Lists are more flexible but may consume more memory due to their dynamic typing and the ability to store different data types.
NumPy Array: NumPy arrays are more memory-efficient as they store elements of the same data type in contiguous memory blocks, leading to better storage and performance.

3.Performance:

List: Lists are generally slower for numerical operations because they are not optimized for mathematical operations.
NumPy Array: NumPy arrays are designed for numerical and scientific computing, and they provide efficient, vectorized operations. This makes them faster for numerical computations compared to lists.

4.Functionality:

List: Lists provide a broad range of built-in methods and functionalities. However, they are not specialized for numerical operations.
NumPy Array: NumPy arrays come with a variety of functions for array manipulation, linear algebra, statistical operations, and more. They are specifically designed for numerical computations.

import numpy as np

## Answers of question 3 to 6


In [23]:
# Creating a array
array=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])

print(f'Shape of array: {array.shape}')       # Shape of array
print(f'Size of array : {array.size}')        # Size of array
print(f'Dimension of array : {array.ndim}\n') # Dimension of array

print(f'First row of array : {array[0,:]}\n') # Accessing the first row of array

print(f'Element at a third row and fourth column  : {array[2,3]}\n')   # Accessing the element at a third row and fourth column

print(f'All the odd indexed element :\n {array[:,1::2]}') # Accessing all the odd indexed element

Shape of array: (3, 4)
Size of array : 12
Dimension of array : 2

First row of array : [1 2 3 4]

Element at a third row and fourth column  : 12

All the odd indexed element :
 [[ 2  4]
 [ 6  8]
 [10 12]]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [29]:
Random_array=np.random.rand(3,3)
print(Random_array)

[[0.63005011 0.12661072 0.36627832]
 [0.08234658 0.1338271  0.66574739]
 [0.60588563 0.79860777 0.31114541]]


## 8. Describe the difference between np.random.rand and np.random.randn?



np.random.rand():
    This function generates random number from a uniform distribution in a range of [0,1].
    
np.random.randn():
    This function generates random number from a standard normal distribution with mean=0 and standard deviation=1.
    

## 9. Write code to increase the dimension of the following array?

In [39]:
# Creating a new array with dimension of 3
# Note: Change the dimension such that product of size and dimension remain same as old one
array1=array.reshape((2,2,3))

print(f'New array : \n{array1}\n')
print(f'Dimension of old array : {array.ndim}')
print(f'Dimension of new array : {array1.ndim}')

New array : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimension of old array : 2
Dimension of new array : 3


## 10. How to transpose the following array in NumPy?

In [42]:
print(f'Original array : \n{array}\n')
print(f'Transpose of array : \n{array.T}')

Original array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose of array : 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [62]:
A=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

B=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

print(f'Index wise multipication : \n{A*B}\n')
print(f'Matrix multipication : \n{A@B.T}\n')   # We want to transpose the matrix B bacause row of A and row of B is not same.
print(f'Add both Matrix : \n{A+B}\n')
print(f'Subtract matrix B from A : \n{A-B}\n')
print(f'Divide matrix B by A : \n{B/A}')

Index wise multipication : 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multipication : 
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Add both Matrix : 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtract matrix B from A : 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Divide matrix B by A : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12.  Which function in Numpy can be used to swap the byte order of an array?

In [66]:
# np.byteswap() function is used to swap the byte order of an array

# Create a NumPy array with integers
original_array = np.array([1, 256, 65536], dtype=np.int32)

# Swap the byte order using byteswap
swapped_array = original_array.byteswap()

# Print the original and swapped arrays
print("Original array:")
print(original_array)

print("\nSwapped array:")
print(swapped_array)

Original array:
[    1   256 65536]

Swapped array:
[16777216    65536      256]


## 13.  What is the significance of the np.linalg.inv function?

In [76]:
# np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix.
# And it has the property that when it is multiplied by the original matrix , the result is the identity matrix.

# Define a square matrix A
A = np.array([[4, 3],
              [1, 2]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Print the original matrix and its inverse
print(f"Original matrix A: \n{A}")

print(f"\nInverse matrix of A:\n{A_inv}")

print(f'\nMultiplication of A and A_inv matrix : \n{np.dot(A,A_inv)}')

Original matrix A: 
[[4 3]
 [1 2]]

Inverse matrix of A:
[[ 0.4 -0.6]
 [-0.2  0.8]]

Multiplication of A and A_inv matrix : 
[[1. 0.]
 [0. 1.]]


## 14. What does the np.reshape function do, and how is it used?

In [4]:
# np.reshape() function is used to change the shape of an array without changing its data. It allows you to rearrange the elements
# of an array into a new shape, provided that the total number of elements remains the same.

arr1=np.array([1,2,3,4,5,6])   # creating array aar1

arr2=np.reshape(arr1,(2,3))    # changing the shape of array arr1

arr3=np.reshape(arr1,(3,-1))   # automatically select the second value of shape by giving -1

print(f'array1 : \n{arr1}\n')
print(f'array2 : \n{arr2}\n')
print(f'array3 : \n{arr3}\n')


array1 : 
[1 2 3 4 5 6]

array2 : 
[[1 2 3]
 [4 5 6]]

array3 : 
[[1 2]
 [3 4]
 [5 6]]



## 15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful feature that allows you to perform operations on arrays of different shapes and sizes. It is a way of treating arrays with different shapes during arithmetic operations, and it helps to avoid the need for explicit loops to perform element-wise operations on arrays of different shapes.

The basic idea behind broadcasting is to extend smaller arrays so that they have compatible shapes for element-wise operations with larger arrays. Broadcasting operates under a set of rules to determine how the dimensions of two arrays should be treated when performing element-wise operations. The smaller array is "broadcast" across the larger array so that they have compatible shapes.

Here are the broadcasting rules:

1. If the arrays have a different number of dimensions, pad the smaller shape with ones on its left side.

2. Compare the sizes of corresponding dimensions. If one of the dimensions is 1, it is stretched to match the size of the other dimension.

3. If sizes along a dimension don't match and neither dimension is 1, then the operation is not possible, and NumPy will raise a ValueError.

In [9]:
# Example 1: Broadcasting with a scalar
arr = np.array([1, 2, 3, 4])
result = arr + 5  # scalar 5 is broadcasted to each element of arr
print(result)
print('\n')

# Example 2: Broadcasting with a 1D array
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2  # both arrays are broadcasted to the same shape
print(result)
print('\n')

# Example 3: Broadcasting with a 2D array and a 1D array
arr3d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
result = arr3d + arr1d  # arr1d is broadcasted to each row of arr3d
print(result)

[6 7 8 9]


[11 22 33]


[[11 22 33]
 [14 25 36]]
